services:
  web:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
      - NEXT_TELEMETRY_DISABLED=1
